enableRobotsTXT = true
theme = "identity"

disableKinds = ['taxonomy', 'term', 'RSS', 'sitemap']
copyright = "2023 Glyzinie"

baseURL = "https://glyzinie.net"
title = "Wis's Profile"

[params]
author = "Wis"
description = "Freelance Engineer"
emoji = "1f408-200d-2b1b"
avatar = "he1gst3audkgfzwgqbpa"

[[params.social]]
name = "Twitter"
icon = "brands fa-x-twitter"
url = "https://twitter.com/intent/user?user_id=1747430158355845120"

[[params.social]]
name = "GitHub"
icon = "brands fa-github"
url = "https://github.com/glyzinie"

[[params.social]]
name = "Zenn"
icon = "solid fa-z"
url = "https://zenn.dev/glyzinie"
